### ISSUE TITLE
Document platform principles

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/platform#1]

**Comment by gilesdring** [comment]
Initial principles captured here

https://open-innovations.github.io/platform/

**Comment by gilesdring** [comment]
@slowe @ChristianSpence I'm making a start on documenting the Open Innovations platform i.e. the jumble of stuff that we sling together to make products:

* R
* python
* dvc
* typescript
* javascript
* Lume
* github pages
* HTML
* CSS
* CSVs
* HexMaps

I've started with the principles we adopt at the highest levels. These are more or less guiding directives, and the aim for these is to be relatively vague, but capture some fundamental approaches.

NB There might be principles at lower levels (e.g. Stuart - we spoke about a principle about building components with inline styles in case we want to render them without the ontaining page stylesheet). I see these being documented closer to the part fo the platform they relate to...

I'd be interested in your feedback or ideas for other principles to include (comments on here is fine, or code changes if you feel so moved!)

Ta.

**Comment by slowe** [comment]
@gilesdring I hadn't seen this notification until now. I've made some tweaks to styles. And I added a mention of "cost" (of end-user's network connections) to Principle 2.
