### ISSUE TITLE
Write up delivery process first draft

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/platform#5]
Create a initial write up of our sprint planning approach to capture some of the discussions we have had in sprint planning meetings. To include

* Regular meetings
* Use of the ticket states and sizing (including risks of taking forward poorly specified tickets)
* Team responsibilities (e.g. who gets to say when a thing is ready)

**Comment by gilesdring** [comment]
Parking as picking up LSIP stuff.

**Comment by gilesdring** [comment]
Initial draft is now online https://open-innovations.github.io/platform/processes/delivery/

@taz-chiles @ODILMichelle @ChristianSpence @luke-strange Would be interested in your feedback - this is an unapologitically early draft. What else do we need to explain here?

**Comment by taz-chiles** [comment]
Looks great - I've just removed an odd typo :) 

There might be something interesting to add about how we are a small delivery team, therefore our individual roles and approach varies depending on the needs of each project. With larger projects, we could say we almost have 'tech lead',  'product owner', 'developer' type responsibilities etc, but I think the fact that we all do some elements of delivery and technical work is unique to Open Innovations and quite interesting to share. I'll have a think about how to put it into words @gilesdring

**Comment by gilesdring** [comment]
I think being explicit about the roles is a great idea. The fact that we don't map people 1:1 to roles is the interesting part.

**Comment by luke-strange** [comment]
I think it's clear and summarises the process (in my short experience) well. I will likely have more to say if I work on a project from start to finish. I found the system we use meant it was really easy for me to join halfway through and pick-up a task to help on the project, as it was broken down into small chunks. 

One thing you could maybe add is about referencing to other tickets if they are useful to finishing that ticket, or similar tasks. I think we started to do this a bit in LSIP.

**Comment by ChristianSpence** [comment]
This looks a great start, @gilesdring: thank you.

Not much to add beyond what others have said, but I do wonder to what extent we should document our approaches, questioning, etc. with clients here. I.e., a process for how we interrogate their needs, hopes and desires both at the beginning of a project but also as it evolves. Perhaps this is about high level aims starting as tickets and slwoly being decomposed into more specific and evolving asks as the project develops?

**Comment by gilesdring** [comment]
Excellent. There's a set of tickets to improve the documentation! Excellent work @ODILMichelle ;-)

**Comment by gilesdring** [comment]
@ChristianSpence Re https://github.com/open-innovations/platform/issues/5#issuecomment-1494060273

Yes - worth documenting the approach to individual project Roadmapping / the product owner role. Definitely some discussions to be had with @ODILMichelle and @taz-chiles here
