### ISSUE TITLE
Create "World of economics" page

### ISSUE THREAD

**Issue by slowe** [open-innovations/platform#8]
We need to create a "World of Economics" page on the website much like the existing https://open-innovations.org/projects/culture/ and https://open-innovations.org/projects/hexmaps/ and https://open-innovations.org/projects/planetdata/ pages. It will link off to all the various economic projects pages or hubs.

- [x] Create a barebones page at, say, https://open-innovations.org/projects/economics/
- [x] Work out how we'd like to arrange the sections
- [x] Link to LSIP
- [x] Link to Tax devolution
- [x] Link to Leeds City Council Economic Data Partner
- [x] Link to JRF North Insight Finder (and perhaps Tom's previous JRF projects).

**Comment by gilesdring** [comment]
To discuss when @slowe is back in - wonder if this ticket is better in the dashboard repo, as that's more closely related to where the changes are. Not urgent - can discuss next week.

**Comment by slowe** [comment]
No, this isn't related to the dashboard.

**Comment by luke-strange** [comment]
@slowe can we move this ticket to done yet?

**Comment by slowe** [comment]
@luke-strange Not really. I invented the sections off the top-of-my-head and nobody more relevant than me has provided any opinions yet. Hence why that isn't ticked off.
