### ISSUE TITLE
Develop a hub page for the University of Leeds/Schools Engagement with Culture project

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/platform#9]
To do:

- [x] Create hub page
- [x] Ensure this is linked to from https://github.com/open-innovations/dashboard/blob/main/data/projects.csv
- [x] Link to repo
- [x] Link to website
- [ ] Draft and publish initial blogpost

**Comment by slowe** [comment]
@ODILMichelle Does this have an existing website and/or repo? It may not necessarily need a specific "hub page" and it may be enough to include links to an existing page from the [World of Culture page](https://open-innovations.org/projects/culture/). I don't know enough about the project to make a decision.

**Comment by ODILMichelle** [comment]
Website is linked to on the project.csv: https://open-innovations.github.io/leeds-schools-cultural-engagement/

Repo exists as that is driving the site, although we've not done anything with data yet. Paul is super keen to get a blog post up, so it probably does need to be a hub page - unless we can add multiple resources on the World of Culture page?

**Comment by slowe** [comment]
I can create a hub page on the website if you want one. I'm just aware that that becomes another place (as well as World of Culture and the Github repo) to remember to keep updated and then you have to keep that updated through someone else. If it was me I'd probably treat the existing Github page as the hub page (to reduce the amount of duplication) and just add one link to that from the World of Culture page.

**Comment by ODILMichelle** [comment]
Perhaps one for us to discuss with the wider team next week, as I know there was certainly eagerness for this to take place.

I know I will struggle to get a blog post written over this sprint (as I'm on holiday for a week), but we can discuss this with the wider team  on Tuesday & work out how we might progress?

**Comment by slowe** [comment]
I've had a chat with Paul and he is happy with the idea that https://open-innovations.github.io/leeds-schools-cultural-engagement/ counts as the "hub page" for the project. His main thing is that "things exist on the web" with a welcome page of some sort. Your existing Github pages site does the introduction and you'll be able to add links to blog posts etc  as you see fit. And it shows up already in our website search e.g. https://open-innovations.org/search/?q=schools so it is findable from our main website. And we can link to it from the "World of Culture" page so there are multiple ways to get to it but only one place that needs regular updating.
